#!/usr/bin/env python3
"""M51 Aufgabe 1: AWS Polly Sample-Generierung.

Liest data/texts.json, fragt Polly describe_voices() ab, synthetisiert
fuer jede Voice × unterstützte EU-Sprache × 3 Varianten ein MP3-Sample.
Output:
  audio/aws/{voice_id}/{lang}_{variant}.mp3
  data/samples.json (append-safe)

Keys aus /root/hermes-workspace/devbrain/.env/aws.env
Mutagen ID3-Tags fuer Attribution (Ghostforge / CC BY 4.0).
"""
from __future__ import annotations

import json
import os
import sys
import time
import traceback
from pathlib import Path

import boto3
from botocore.exceptions import ClientError

ROOT = Path(__file__).resolve().parent.parent
ENV_DIR = Path("/root/hermes-workspace/devbrain/.env")
AUDIO_DIR = ROOT / "audio"
SAMPLES_JSON = ROOT / "data" / "samples.json"
TEXTS_JSON = ROOT / "data" / "texts.json"

VARIANTS = ["v1_simple", "v2_medium", "v3_emotional"]
MAX_RETRIES = 2

# Polly LanguageCode -> ISO short code
POLLY_LANG_MAP = {
    "arb": None, "ca-ES": "ca", "cmn-CN": "zh", "cy-GB": None,
    "da-DK": "da", "de-AT": "de", "de-DE": "de", "el-GR": "el",
    "en-AU": "en", "en-GB": "en", "en-IE": "en", "en-IN": "en",
    "en-NZ": "en", "en-US": "en", "en-ZA": "en",
    "es-ES": "es", "es-MX": "es", "es-US": "es",
    "eu-ES": None, "fa-IR": None, "fi-FI": "fi", "fil-PH": None,
    "fr-CA": "fr", "fr-FR": "fr",
    "gl-ES": None, "he-IL": None, "hi-IN": "hi",
    "hr-HR": "hr", "hu-HU": "hu", "is-IS": None, "it-IT": "it",
    "ja-JP": "ja", "ko-KR": "ko",
    "lt-LT": None, "lv-LV": None, "ms-MY": None,
    "mt-MT": "mt", "nb-NO": "no", "nl-BE": "nl", "nl-NL": "nl",
    "pl-PL": "pl", "pt-BR": "pt", "pt-PT": "pt",
    "ro-RO": "ro", "ru-RU": "ru", "sk-SK": "sk", "sl-SI": "sl",
    "sv-SE": "sv", "th-TH": None, "tr-TR": "tr",
    "uk-UA": None, "vi-VN": None, "yue-CN": "zh",
    # Neue EU-Sprachen falls Polly sie ergänzt
    "cs-CZ": "cs", "et-EE": "et", "ga-IE": "ga",
    "bg-BG": "bg", "hu-HU": "hu", "el-GR": "el",
    "lv-LV": "lv", "lt-LT": "lt",
}


def _env_file(name: str) -> dict[str, str]:
    path = ENV_DIR / name
    if not path.exists():
        return {}
    out: dict[str, str] = {}
    for line in path.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        k, v = line.split("=", 1)
        out[k.strip()] = v.strip()
    return out


def _tag_mp3(path: Path, provider: str, voice_name: str) -> None:
    """ID3-Tag mit Ghostforge/CC BY 4.0 Attribution."""
    try:
        from mutagen.mp3 import MP3  # type: ignore
        from mutagen.id3 import ID3, TPE1, COMM, TCOP  # type: ignore
        try:
            audio = MP3(str(path))
            if audio.tags is None:
                audio.add_tags()
            tag = audio.tags
        except Exception:
            tag = ID3()
        tag.add(TPE1(encoding=3, text=["Ghostforge"]))
        tag.add(COMM(encoding=3, lang="eng", desc="Source",
                     text=[f"Generated by voice-test.dev -- {provider} {voice_name}"]))
        tag.add(TCOP(encoding=3, text=["CC BY 4.0 -- voice-test.dev"]))
        if isinstance(tag, ID3):
            tag.save(str(path))
        else:
            audio.save()
    except Exception as e:
        print(f"    [tag warn] {path.name}: {e}", flush=True)


def discover_voices(client) -> list[dict]:
    """Alle Polly-Stimmen abfragen, auf EU-Sprachen filtern."""
    print("Polly describe_voices()...", flush=True)
    seen: dict[str, dict] = {}
    for lang_code in POLLY_LANG_MAP.keys():
        try:
            resp = client.describe_voices(LanguageCode=lang_code)
            for v in resp.get("Voices", []):
                vid = v["Id"]
                if vid in seen:
                    # weitere Sprache fuer dieselbe Voice
                    short = POLLY_LANG_MAP.get(lang_code)
                    if short and short not in seen[vid]["languages"]:
                        seen[vid]["languages"].append(short)
                    continue
                short = POLLY_LANG_MAP.get(lang_code)
                seen[vid] = {
                    "id": vid,
                    "name": v.get("Name", vid),
                    "gender": v.get("Gender", "unknown"),
                    "language_code": lang_code,
                    "engine": v.get("SupportedEngines", ["standard"]),
                    "languages": [short] if short else [],
                }
        except ClientError as e:
            # manche LanguageCodes sind bei Polly ungueltig -> ueberspringen
            if "UnknownValueException" in str(type(e)) or "UnknownValue" in str(e):
                continue
            print(f"    [warn] describe_voices({lang_code}): {e}", flush=True)
    voices = [v for v in seen.values() if v["languages"]]
    print(f"  {len(voices)} Stimmen mit EU-Sprachen gefunden", flush=True)
    return voices


def synth_one(client, voice: dict, engine: str, lang_short: str, variant: str,
              text: str, out_path: Path) -> int:
    """Eine Synthese mit expliziter Engine, gibt Audio-Laenge in ms zurueck.

    M52: JEDE unterstuetzte Engine wird separat synthetisiert (standard,
    neural, generative). Kein Fallback mehr auf standard.
    """
    t0 = time.monotonic()
    for attempt in range(1, MAX_RETRIES + 2):
        try:
            kwargs = dict(
                Engine=engine,
                Text=text,
                OutputFormat="mp3",
                VoiceId=voice["id"],
                SampleRate="24000",
            )
            # Engine-Parameter nur setzen, wenn die Stimme diese Engine
            # unterstuetzt (sonst InvalidParameterCombination).
            try:
                resp = client.synthesize_speech(**kwargs)
            except ClientError as e:
                # Manche Stimmen wollen keinen Engine-Parameter bei standard.
                if "InvalidParameterCombination" in str(type(e)) and engine == "standard":
                    kwargs.pop("Engine")
                    resp = client.synthesize_speech(**kwargs)
                else:
                    raise
            audio_stream = resp["AudioStream"].read()
            if len(audio_stream) < 256:
                raise RuntimeError("leere Audio-Antwort")
            out_path.write_bytes(audio_stream)
            return int((time.monotonic() - t0) * 1000)
        except ClientError:
            if attempt > MAX_RETRIES:
                raise
            time.sleep(1.5 * attempt)
    return int((time.monotonic() - t0) * 1000)


def load_existing_samples() -> list[dict]:
    if not SAMPLES_JSON.exists():
        return []
    try:
        return json.loads(SAMPLES_JSON.read_text(encoding="utf-8")).get("samples", [])
    except Exception:
        return []


def save_samples(existing: list[dict], new_samples: list[dict]) -> None:
    all_samples = existing + new_samples
    SAMPLES_JSON.write_text(
        json.dumps({"_meta": {
            "generated_at": time.strftime("%Y-%m-%dT%H:%M:%S%z"),
            "total": len(all_samples),
        }, "samples": all_samples}, ensure_ascii=False, indent=2),
        encoding="utf-8",
    )


def main() -> int:
    env = _env_file("aws.env")
    if not env:
        print("FEHLER: aws.env nicht gefunden", flush=True)
        return 1

    texts = json.loads(TEXTS_JSON.read_text(encoding="utf-8"))
    available_langs = set(texts["texts"]["v1_simple"].keys())

    session = boto3.session.Session(
        aws_access_key_id=env["AWS_ACCESS_KEY_ID"],
        aws_secret_access_key=env["AWS_SECRET_ACCESS_KEY"],
        region_name=env.get("AWS_DEFAULT_REGION", "eu-central-1"),
    )
    client = session.client("polly")

    voices = discover_voices(client)

    # M52: Alte AWS-Samples mit old-ID-Schema (ohne engine) verwerfen,
    # weil wir JEDE Engine separat erfassen. sample-id schema neu:
    #   aws-{voice_id}-{engine}-{lang}-{variant}
    old_existing = load_existing_samples()
    existing = [s for s in old_existing
                if not (s.get("provider") == "aws"
                        and f"-{s.get('language')}-v" in s.get("id", "")
                        and f"-{s.get('model_type', 'neural' if 'neural' in str(s.get('engine','')) else 'standard')}-" not in s.get("id", ""))]
    # Simplerer Filter: alle alten aws-Samples verwerfen, neuer Lauf generiert neu
    existing = [s for s in old_existing if s.get("provider") != "aws"]
    existing_ids = {s["id"] for s in existing}
    new_samples: list[dict] = []
    counters = {"ok": 0, "skip": 0, "err": 0}
    errors: list[str] = []

    # M52: Pro Stimme × JEDE unterstuetzte Engine × Sprache × 3 Varianten
    ENGINES = ["generative", "neural", "standard"]
    plan_total = 0
    for v in voices:
        for engine in ENGINES:
            if engine not in v["engine"]:
                continue
            for lang in v["languages"]:
                if lang not in available_langs:
                    continue
                plan_total += len(VARIANTS)
    print(f"Plan: {plan_total} Samples "
          f"({len(voices)} Stimmen × alle Engines × bis zu 3 Varianten)",
          flush=True)

    for v in voices:
        voice_id = v["id"]
        safe_voice = "".join(c if c.isalnum() or c in "-_" else "_" for c in voice_id)
        out_dir = AUDIO_DIR / "aws" / safe_voice
        out_dir.mkdir(parents=True, exist_ok=True)
        for engine in ENGINES:
            if engine not in v["engine"]:
                continue
            for lang in v["languages"]:
                if lang not in available_langs:
                    continue
                for variant in VARIANTS:
                    text = texts["texts"][variant].get(lang)
                    if not text:
                        continue
                    sid = f"aws-{safe_voice}-{engine}-{lang}-{variant}"
                    out_path = out_dir / f"{engine}_{lang}_{variant}.mp3"
                    if sid in existing_ids:
                        counters["skip"] += 1
                        continue
                    if out_path.exists() and out_path.stat().st_size > 1024:
                        # Datei auf Disk, aber nicht in samples.json -> Metadaten nachtragen
                        new_samples.append({
                            "id": sid,
                            "provider": "aws",
                            "provider_display": "Amazon Polly",
                            "voice_id": voice_id,
                            "voice_name": v["name"],
                            "language": lang,
                            "language_name": next(
                                (l["name"] for l in texts.get("languages", [])
                                 if l.get("code") == lang), lang),
                            "variant": variant,
                            "gender": v["gender"],
                            "engine": engine,
                            "model_type": engine,
                            "model_size_mb": None,
                            "audio_path": str(out_path.relative_to(ROOT)),
                            "provider_url": "https://aws.amazon.com/polly/",
                            "license": "proprietary",
                            "generation_time_ms": None,
                            "sample_rate": 24000,
                        })
                        counters["skip"] += 1
                        continue
                    try:
                        ms = synth_one(client, v, engine, lang, variant, text, out_path)
                        _tag_mp3(out_path, "aws", f"{v['name']} ({engine})")
                        new_samples.append({
                            "id": sid,
                            "provider": "aws",
                            "provider_display": "Amazon Polly",
                            "voice_id": voice_id,
                            "voice_name": v["name"],
                            "language": lang,
                            "language_name": next(
                                (l["name"] for l in texts.get("languages", [])
                                 if l.get("code") == lang), lang),
                            "variant": variant,
                            "gender": v["gender"],
                            "engine": engine,
                            "model_type": engine,
                            "model_size_mb": None,
                            "audio_path": str(out_path.relative_to(ROOT)),
                            "provider_url": "https://aws.amazon.com/polly/",
                            "license": "proprietary",
                            "generation_time_ms": ms,
                            "sample_rate": 24000,
                        })
                        counters["ok"] += 1
                    except Exception as e:
                        counters["err"] += 1
                        errors.append(f"aws/{voice_id}/{engine}/{lang}_{variant}: {e}")
                        if out_path.exists():
                            try:
                                out_path.unlink()
                            except Exception:
                                pass

            done = counters["ok"] + counters["err"] + counters["skip"]
            if done % 30 < len(VARIANTS):
                print(f"  Progress: {done}/{plan_total} "
                      f"(ok={counters['ok']}, skip={counters['skip']}, err={counters['err']})",
                      flush=True)

    save_samples(existing, new_samples)
    print(f"\nFertig: ok={counters['ok']}, skip={counters['skip']}, err={counters['err']}",
          flush=True)
    if errors:
        print(f"Fehler ({len(errors)}):")
        for e in errors[:20]:
            print(f"  - {e}")
    return 0 if not errors else 1


if __name__ == "__main__":
    sys.exit(main())
