#!/usr/bin/env python3
"""M52 S1c: Azure TTS - ALLE Stimmen mit multilingual Support.

Holt /cognitiveservices/voices/list, beruecksichtigt fuer jede Stimme:
  - Locale (Primary)
  - SecondaryLocaleList (Multilingual Voices, z.B. zh-CN-XiaochenMultilingual)
Pro Stimme × jede EU-Sprache × 3 Varianten -> MP3.

Ersetzt die M51 Azure-Samples (die nur Primary-Locale beruecksichtigten).

Output:
  audio/azure/{voice_id}/{lang}_{variant}.mp3
  data/samples.json (existing azure-Samples werden gefiltert)
"""
from __future__ import annotations

import asyncio
import json
import sys
import time
from pathlib import Path

import httpx

ROOT = Path(__file__).resolve().parent.parent
ENV_DIR = Path("/root/hermes-workspace/devbrain/.env")
AUDIO_DIR = ROOT / "audio"
SAMPLES_JSON = ROOT / "data" / "samples.json"
TEXTS_JSON = ROOT / "data" / "texts.json"

VARIANTS = ["v1_simple", "v2_medium", "v3_emotional"]
MAX_RETRIES = 2
CONCURRENCY = 5

# EU-Sprachen (BCP-47 Region-Codes, die Azure liefert)
EU_LOCALES = {
    "bg-BG", "cs-CZ", "da-DK", "de-AT", "de-DE", "el-GR",
    "en-GB", "en-IE", "en-US",
    "es-ES", "et-EE", "fi-FI",
    "fr-BE", "fr-FR", "fr-CA",
    "ga-IE", "hr-HR", "hu-HU",
    "it-IT", "lt-LT", "lv-LV", "mt-MT",
    "nb-NO", "nl-BE", "nl-NL",
    "pl-PL", "pt-PT", "pt-BR",
    "ro-RO", "sk-SK", "sl-SI", "sv-SE",
}

# BCP-47 -> ISO short code ( mappings fuer unsere texts.json)
LOCALE_TO_SHORT = {
    "bg-BG": "bg", "cs-CZ": "cs", "da-DK": "da", "de-AT": "de", "de-DE": "de",
    "el-GR": "el", "en-GB": "en", "en-IE": "en", "en-US": "en",
    "es-ES": "es", "et-EE": "et", "fi-FI": "fi",
    "fr-BE": "fr", "fr-FR": "fr", "fr-CA": "fr",
    "ga-IE": "ga", "hr-HR": "hr", "hu-HU": "hu",
    "it-IT": "it", "lt-LT": "lt", "lv-LV": "lv", "mt-MT": "mt",
    "nb-NO": "no", "nl-BE": "nl", "nl-NL": "nl",
    "pl-PL": "pl", "pt-PT": "pt", "pt-BR": "pt",
    "ro-RO": "ro", "sk-SK": "sk", "sl-SI": "sl", "sv-SE": "sv",
}


def _env_file(name: str) -> dict[str, str]:
    path = ENV_DIR / name
    if not path.exists():
        return {}
    out: dict[str, str] = {}
    for line in path.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        k, v = line.split("=", 1)
        out[k.strip()] = v.strip()
    return out


def _tag_mp3(path: Path, provider: str, voice_name: str) -> None:
    try:
        from mutagen.mp3 import MP3  # type: ignore
        from mutagen.id3 import ID3, TPE1, COMM, TCOP  # type: ignore
        try:
            audio = MP3(str(path))
            if audio.tags is None:
                audio.add_tags()
            tag = audio.tags
        except Exception:
            tag = ID3()
        tag.add(TPE1(encoding=3, text=["Ghostforge"]))
        tag.add(COMM(encoding=3, lang="eng", desc="Source",
                     text=[f"Generated by voice-test.dev -- {provider} {voice_name}"]))
        tag.add(TCOP(encoding=3, text=["CC BY 4.0 -- voice-test.dev"]))
        if isinstance(tag, ID3):
            tag.save(str(path))
        else:
            audio.save()
    except Exception as e:
        print(f"    [tag warn] {path.name}: {e}", flush=True)


async def fetch_voices(client: httpx.AsyncClient, env: dict) -> list[dict]:
    region = env["AZURE_SPEECH_REGION"]
    key = env["AZURE_SPEECH_KEY"]
    r = await client.get(
        f"https://{region}.tts.speech.microsoft.com/cognitiveservices/voices/list",
        headers={"Ocp-Apim-Subscription-Key": key},
        timeout=60.0,
    )
    if r.status_code != 200:
        raise RuntimeError(f"voices/list HTTP {r.status_code}: {r.text[:200]}")
    return r.json()


def filter_eu_voices(all_voices: list[dict]) -> list[dict]:
    """Behalte nur Stimmen mit mind. 1 EU-Sprache (Primary oder Secondary).

    Liefert erweiterte voice-dicts mit 'eu_locales' (Liste von BCP-47).
    """
    out = []
    for v in all_voices:
        # Deprecated-Stimmen weglassen
        if v.get("Status") == "Deprecated":
            continue
        primary = v.get("Locale")
        secondary = v.get("SecondaryLocaleList", []) or []
        all_locs = {primary, *secondary}
        eu = all_locs & EU_LOCALES
        if eu:
            v2 = dict(v)
            v2["eu_locales"] = sorted(eu)
            out.append(v2)
    return out


async def synth_one(
    client: httpx.AsyncClient,
    env: dict,
    voice: dict,
    locale: str,
    variant: str,
    text: str,
    out_path: Path,
) -> int:
    region = env["AZURE_SPEECH_REGION"]
    key = env["AZURE_SPEECH_KEY"]
    voice_name = voice["ShortName"]
    # SSML mit xml:lang der Zielsprache (wichtig fuer Multilingual!)
    ssml = (
        f"<speak version='1.0' xml:lang='{locale}'>"
        f"<voice name='{voice_name}'>{text}</voice></speak>"
    )
    t0 = time.monotonic()
    for attempt in range(1, MAX_RETRIES + 2):
        try:
            r = await client.post(
                f"https://{region}.tts.speech.microsoft.com/cognitiveservices/v1",
                headers={
                    "Ocp-Apim-Subscription-Key": key,
                    "Content-Type": "application/ssml+xml",
                    "X-Microsoft-OutputFormat": "audio-24khz-48kbitrate-mono-mp3",
                },
                content=ssml, timeout=60.0,
            )
            if r.status_code != 200:
                raise RuntimeError(f"azure HTTP {r.status_code}: {r.text[:120]}")
            if len(r.content) < 256:
                raise RuntimeError("leere Audio-Antwort")
            out_path.write_bytes(r.content)
            return int((time.monotonic() - t0) * 1000)
        except (httpx.HTTPError, RuntimeError):
            if attempt > MAX_RETRIES:
                raise
            await asyncio.sleep(1.0 * attempt)
    return int((time.monotonic() - t0) * 1000)


def _voice_type(v: dict) -> str:
    """VoiceType + Multi-Flag kombinieren."""
    vt = (v.get("VoiceType") or "Neural").lower()
    if v.get("SecondaryLocaleList"):
        return f"{vt}-multilingual"
    return vt


async def main() -> int:
    env = _env_file("azure.env")
    if not env or "AZURE_SPEECH_KEY" not in env:
        print("FEHLER: azure.env unvollstaendig", flush=True)
        return 1

    texts = json.loads(TEXTS_JSON.read_text(encoding="utf-8"))
    available_langs = set(texts["texts"]["v1_simple"].keys())

    async with httpx.AsyncClient() as client:
        all_voices = await fetch_voices(client, env)
        print(f"Azure: {len(all_voices)} Stimmen total", flush=True)
        voices = filter_eu_voices(all_voices)
        print(f"  {len(voices)} Stimmen mit EU-Sprachen "
              f"(inkl. Multilingual)", flush=True)

        # Alte azure-Samples verwerfen, M52 generiert konsistent neu
        existing_raw = []
        if SAMPLES_JSON.exists():
            try:
                existing_raw = json.loads(
                    SAMPLES_JSON.read_text(encoding="utf-8")
                ).get("samples", [])
            except Exception:
                pass
        existing = [s for s in existing_raw if s.get("provider") != "azure"]
        existing_ids = {s["id"] for s in existing}
        print(f"  Bestand ohne azure: {len(existing)} Samples", flush=True)

        # Job-Plan: voice × eu_locale × variant
        plan_jobs: list[tuple] = []
        for v in voices:
            short_name = v["ShortName"]
            safe_voice = "".join(
                c if c.isalnum() or c in "-_" else "_" for c in short_name
            )
            for locale in v["eu_locales"]:
                short = LOCALE_TO_SHORT.get(locale)
                if not short or short not in available_langs:
                    continue
                text = texts["texts"]["v1_simple"].get(short)
                if not text:
                    continue
                for variant in VARIANTS:
                    sid = f"azure-{short_name}-{locale}-{variant}"
                    out_path = (
                        AUDIO_DIR / "azure" / safe_voice
                        / f"{locale}_{variant}.mp3"
                    )
                    if sid in existing_ids:
                        continue
                    if out_path.exists() and out_path.stat().st_size > 1024:
                        continue
                    plan_jobs.append((v, locale, short, variant, sid, out_path))

        print(f"Plan: {len(plan_jobs)} Samples zu generieren", flush=True)
        if not plan_jobs:
            print("  Nichts zu tun.", flush=True)
            # Trotzdem samples.json neu schreiben (azure gefiltert)
            _write_samples(existing, [])
            return 0

        sem = asyncio.Semaphore(CONCURRENCY)
        counters = {"ok": 0, "err": 0}
        errors: list[str] = []
        new_samples: list[dict] = []
        done = 0

        async def worker(v, locale, short, variant, sid, out_path):
            nonlocal done
            async with sem:
                out_path.parent.mkdir(parents=True, exist_ok=True)
                text = texts["texts"][variant].get(short)
                try:
                    ms = await synth_one(
                        client, env, v, locale, variant, text, out_path,
                    )
                    _tag_mp3(out_path, "azure", v["ShortName"])
                    short_name = v["ShortName"]
                    safe_voice = "".join(
                        c if c.isalnum() or c in "-_" else "_" for c in short_name
                    )
                    new_samples.append({
                        "id": sid,
                        "provider": "azure",
                        "provider_display": "Microsoft Azure TTS",
                        "voice_id": short_name,
                        "voice_name": v.get("DisplayName", short_name),
                        "language": short,
                        "language_name": next(
                            (l["name"] for l in texts.get("languages", [])
                             if l.get("code") == short), short),
                        "locale": locale,
                        "variant": variant,
                        "gender": (v.get("Gender") or "Unknown").lower(),
                        "model_type": _voice_type(v),
                        "model_size_mb": None,
                        "audio_path": str(out_path.relative_to(ROOT)),
                        "provider_url": "https://azure.microsoft.com/products/ai-services/text-to-speech",
                        "license": "proprietary",
                        "generation_time_ms": ms,
                        "sample_rate": 24000,
                    })
                    counters["ok"] += 1
                except Exception as e:
                    counters["err"] += 1
                    errors.append(f"azure/{v['ShortName']}/{locale}_{variant}: {e}")
                    if out_path.exists():
                        try:
                            out_path.unlink()
                        except Exception:
                            pass
                done += 1
                if done % 100 == 0:
                    print(f"  Progress: {done}/{len(plan_jobs)} "
                          f"(ok={counters['ok']}, err={counters['err']})",
                          flush=True)

        tasks = [worker(*job) for job in plan_jobs]
        for i in range(0, len(tasks), 80):
            await asyncio.gather(*tasks[i:i + 80])

    # Disk-Sync: Stimmen, die schon auf Disk liegen, in samples.json aufnehmen
    for v in voices:
        short_name = v["ShortName"]
        safe_voice = "".join(
            c if c.isalnum() or c in "-_" else "_" for c in short_name
        )
        for locale in v["eu_locales"]:
            short = LOCALE_TO_SHORT.get(locale)
            if not short or short not in available_langs:
                continue
            for variant in VARIANTS:
                sid = f"azure-{short_name}-{locale}-{variant}"
                if sid in existing_ids:
                    continue
                if any(s["id"] == sid for s in new_samples):
                    continue
                out_path = (
                    AUDIO_DIR / "azure" / safe_voice
                    / f"{locale}_{variant}.mp3"
                )
                if out_path.exists() and out_path.stat().st_size > 1024:
                    new_samples.append({
                        "id": sid,
                        "provider": "azure",
                        "provider_display": "Microsoft Azure TTS",
                        "voice_id": short_name,
                        "voice_name": v.get("DisplayName", short_name),
                        "language": short,
                        "language_name": next(
                            (l["name"] for l in texts.get("languages", [])
                             if l.get("code") == short), short),
                        "locale": locale,
                        "variant": variant,
                        "gender": (v.get("Gender") or "Unknown").lower(),
                        "model_type": _voice_type(v),
                        "model_size_mb": None,
                        "audio_path": str(out_path.relative_to(ROOT)),
                        "provider_url": "https://azure.microsoft.com/products/ai-services/text-to-speech",
                        "license": "proprietary",
                        "generation_time_ms": None,
                        "sample_rate": 24000,
                    })

    _write_samples(existing, new_samples)
    print(f"\nFertig: ok={counters['ok']}, err={counters['err']}", flush=True)
    if errors:
        print(f"Fehler ({len(errors)}):")
        for e in errors[:20]:
            print(f"  - {e}")
    return 0 if not errors else 1


def _write_samples(existing: list[dict], new_samples: list[dict]) -> None:
    all_samples = existing + new_samples
    SAMPLES_JSON.write_text(
        json.dumps({"_meta": {
            "generated_at": time.strftime("%Y-%m-%dT%H:%M:%S%z"),
            "total": len(all_samples),
        }, "samples": all_samples}, ensure_ascii=False, indent=2),
        encoding="utf-8",
    )
    print(f"samples.json: {len(all_samples)} Samples total", flush=True)


if __name__ == "__main__":
    sys.exit(asyncio.run(main()))
