#!/usr/bin/env python3
"""M52 S1e: Edge TTS - ALLE 96 EU-relevanten Stimmen.

Edge TTS ist kostenlos und unlimitiert (Microsofts Edge-Browser TTS).
Holt list_voices(), filtert auf EU-Sprachen, generiert 3 Varianten.

Output:
  audio/edge/{voice_id}/{lang}_{variant}.mp3
  data/samples.json (existing edge-Samples werden gefiltert)
"""
from __future__ import annotations

import asyncio
import json
import sys
import time
from pathlib import Path

import edge_tts
import httpx

ROOT = Path(__file__).resolve().parent.parent
AUDIO_DIR = ROOT / "audio"
SAMPLES_JSON = ROOT / "data" / "samples.json"
TEXTS_JSON = ROOT / "data" / "texts.json"

VARIANTS = ["v1_simple", "v2_medium", "v3_emotional"]
MAX_RETRIES = 2
CONCURRENCY = 8

EU_LOCALES = {
    "bg-BG": "bg", "cs-CZ": "cs", "da-DK": "da", "de-AT": "de", "de-DE": "de",
    "el-GR": "el", "en-GB": "en", "en-IE": "en", "en-US": "en",
    "es-ES": "es", "et-EE": "et", "fi-FI": "fi",
    "fr-BE": "fr", "fr-FR": "fr", "fr-CA": "fr",
    "ga-IE": "ga", "hr-HR": "hr", "hu-HU": "hu",
    "it-IT": "it", "lt-LT": "lt", "lv-LV": "lv", "mt-MT": "mt",
    "nb-NO": "no", "nl-BE": "nl", "nl-NL": "nl",
    "pl-PL": "pl", "pt-PT": "pt", "pt-BR": "pt",
    "ro-RO": "ro", "sk-SK": "sk", "sl-SI": "sl", "sv-SE": "sv",
}


def _tag_mp3(path: Path, provider: str, voice_name: str) -> None:
    try:
        from mutagen.mp3 import MP3  # type: ignore
        from mutagen.id3 import ID3, TPE1, COMM, TCOP  # type: ignore
        try:
            audio = MP3(str(path))
            if audio.tags is None:
                audio.add_tags()
            tag = audio.tags
        except Exception:
            tag = ID3()
        tag.add(TPE1(encoding=3, text=["Ghostforge"]))
        tag.add(COMM(encoding=3, lang="eng", desc="Source",
                     text=[f"Generated by voice-test.dev -- {provider} {voice_name}"]))
        tag.add(TCOP(encoding=3, text=["CC BY 4.0 -- voice-test.dev"]))
        if isinstance(tag, ID3):
            tag.save(str(path))
        else:
            audio.save()
    except Exception as e:
        print(f"    [tag warn] {path.name}: {e}", flush=True)


async def list_eu_voices() -> list[dict]:
    all_voices = await edge_tts.list_voices()
    eu = []
    for v in all_voices:
        locale = v.get("Locale")
        short = EU_LOCALES.get(locale)
        if not short:
            continue
        v2 = dict(v)
        v2["short_lang"] = short
        eu.append(v2)
    return eu


async def synth_one(
    voice_id: str, text: str, out_path: Path,
) -> int:
    t0 = time.monotonic()
    for attempt in range(1, MAX_RETRIES + 2):
        try:
            comm = edge_tts.Communicate(text, voice_id)
            await comm.save(str(out_path))
            if not out_path.exists() or out_path.stat().st_size < 256:
                raise RuntimeError("leere Audio-Antwort")
            return int((time.monotonic() - t0) * 1000)
        except Exception:
            if attempt > MAX_RETRIES:
                raise
            await asyncio.sleep(1.0 * attempt)
    return int((time.monotonic() - t0) * 1000)


async def main() -> int:
    texts = json.loads(TEXTS_JSON.read_text(encoding="utf-8"))
    available_langs = set(texts["texts"]["v1_simple"].keys())

    voices = await list_eu_voices()
    print(f"Edge EU-relevant: {len(voices)} Stimmen", flush=True)

    existing_raw = []
    if SAMPLES_JSON.exists():
        try:
            existing_raw = json.loads(
                SAMPLES_JSON.read_text(encoding="utf-8")
            ).get("samples", [])
        except Exception:
            pass
    existing = [s for s in existing_raw if s.get("provider") != "edge"]
    existing_ids = {s["id"] for s in existing}
    print(f"Bestand ohne edge: {len(existing)} Samples", flush=True)

    # Job-Plan
    plan_jobs: list[tuple] = []
    for v in voices:
        short_name = v["ShortName"]
        safe_voice = "".join(
            c if c.isalnum() or c in "-_" else "_" for c in short_name
        )
        short = v["short_lang"]
        if short not in available_langs:
            continue
        for variant in VARIANTS:
            sid = f"edge-{short_name}-{short}-{variant}"
            out_path = AUDIO_DIR / "edge" / safe_voice / f"{short}_{variant}.mp3"
            if sid in existing_ids:
                continue
            if out_path.exists() and out_path.stat().st_size > 1024:
                continue
            text = texts["texts"][variant].get(short)
            if not text:
                continue
            plan_jobs.append((v, short, variant, text, sid, out_path))

    print(f"Plan: {len(plan_jobs)} Samples zu generieren", flush=True)
    if not plan_jobs:
        print("  Nichts zu tun.")
        _write_samples(existing, [])
        return 0

    sem = asyncio.Semaphore(CONCURRENCY)
    counters = {"ok": 0, "err": 0}
    errors: list[str] = []
    new_samples: list[dict] = []
    done = 0

    async def worker(v, short, variant, text, sid, out_path):
        nonlocal done
        async with sem:
            out_path.parent.mkdir(parents=True, exist_ok=True)
            try:
                ms = await synth_one(v["ShortName"], text, out_path)
                _tag_mp3(out_path, "edge", v["ShortName"])
                safe_voice = "".join(
                    c if c.isalnum() or c in "-_" else "_"
                    for c in v["ShortName"]
                )
                new_samples.append({
                    "id": sid,
                    "provider": "edge",
                    "provider_display": "Microsoft Edge TTS",
                    "voice_id": v["ShortName"],
                    "voice_name": v.get("FriendlyName", v["ShortName"]),
                    "language": short,
                    "language_name": next(
                        (l["name"] for l in texts.get("languages", [])
                         if l.get("code") == short), short),
                    "locale": v["Locale"],
                    "variant": variant,
                    "gender": (v.get("Gender") or "Unknown").lower(),
                    "model_type": "edge-neural",
                    "model_size_mb": None,
                    "audio_path": str(out_path.relative_to(ROOT)),
                    "provider_url": "https://www.microsoft.com/edge",
                    "license": "proprietary",
                    "generation_time_ms": ms,
                    "sample_rate": 24000,
                })
                counters["ok"] += 1
            except Exception as e:
                counters["err"] += 1
                errors.append(f"edge/{v['ShortName']}/{short}_{variant}: {e}")
                if out_path.exists():
                    try:
                        out_path.unlink()
                    except Exception:
                        pass
            done += 1
            if done % 50 == 0:
                print(f"  Progress: {done}/{len(plan_jobs)} "
                      f"(ok={counters['ok']}, err={counters['err']})",
                      flush=True)

    tasks = [worker(*job) for job in plan_jobs]
    for i in range(0, len(tasks), 80):
        await asyncio.gather(*tasks[i:i + 80])

    # Disk-Sync über ALLE audio/edge/* directories (nicht nur voices)
    audio_edge = AUDIO_DIR / "edge"
    if audio_edge.exists():
        for voice_dir in audio_edge.iterdir():
            if not voice_dir.is_dir():
                continue
            short_name = voice_dir.name
            for mp3 in voice_dir.glob("*.mp3"):
                # filename: {short}_{variant}.mp3
                stem = mp3.stem
                if "_" not in stem:
                    continue
                parts = stem.split("_", 1)
                short, variant = parts[0], parts[1]
                sid = f"edge-{short_name}-{short}-{variant}"
                if sid in existing_ids:
                    continue
                if any(s["id"] == sid for s in new_samples):
                    continue
                # Voice-Info nachschlagen
                v_info = next((v for v in voices if v["ShortName"] == short_name), None)
                gender = (v_info["Gender"] if v_info else "Unknown").lower()
                new_samples.append({
                    "id": sid,
                    "provider": "edge",
                    "provider_display": "Microsoft Edge TTS",
                    "voice_id": short_name,
                    "voice_name": v_info["FriendlyName"] if v_info else short_name,
                    "language": short,
                    "language_name": next(
                        (l["name"] for l in texts.get("languages", [])
                         if l.get("code") == short), short),
                    "locale": v_info["Locale"] if v_info else short,
                    "variant": variant,
                    "gender": gender,
                    "model_type": "edge-neural",
                    "model_size_mb": None,
                    "audio_path": str(mp3.relative_to(ROOT)),
                    "provider_url": "https://www.microsoft.com/edge",
                    "license": "proprietary",
                    "generation_time_ms": None,
                    "sample_rate": 24000,
                })

    _write_samples(existing, new_samples)
    print(f"\nFertig: ok={counters['ok']}, err={counters['err']}", flush=True)
    if errors:
        print(f"Fehler ({len(errors)}):")
        for e in errors[:20]:
            print(f"  - {e}")
    return 0 if not errors else 1


def _write_samples(existing: list[dict], new_samples: list[dict]) -> None:
    all_samples = existing + new_samples
    SAMPLES_JSON.write_text(
        json.dumps({"_meta": {
            "generated_at": time.strftime("%Y-%m-%dT%H:%M:%S%z"),
            "total": len(all_samples),
        }, "samples": all_samples}, ensure_ascii=False, indent=2),
        encoding="utf-8",
    )
    print(f"samples.json: {len(all_samples)} Samples total", flush=True)


if __name__ == "__main__":
    sys.exit(asyncio.run(main()))
