#!/usr/bin/env python3
"""M52 S1d: ElevenLabs - Default Voices + Voice Library.

Der groesste M51-Fehler: nur 2 Stimmen. M52 holt:
  1. Default Voices (21)
  2. Voice Library paginiert, sortiert nach Nutzung (usage_character_count_1y)
  3. Budget-Limit hart: 40k chars/Monat (Starter Tier)
     3 Varianten × ~100 chars = ~300 chars pro Stimme -> ~98 Stimmen

Prioritaet: DE female zuerst, dann DE male, dann EN/FR/ES/IT.
Output:
  audio/elevenlabs/{voice_id}/{lang}_{variant}.mp3
  data/samples.json (existing elevenlabs-Samples werden gefiltert)
"""
from __future__ import annotations

import asyncio
import json
import sys
import time
from pathlib import Path

import httpx

ROOT = Path(__file__).resolve().parent.parent
ENV_DIR = Path("/root/hermes-workspace/devbrain/.env")
AUDIO_DIR = ROOT / "audio"
SAMPLES_JSON = ROOT / "data" / "samples.json"
TEXTS_JSON = ROOT / "data" / "texts.json"

VARIANTS = ["v1_simple", "v2_medium", "v3_emotional"]
MAX_RETRIES = 2
CONCURRENCY = 1  # ElevenLabs ist streng rate-limited, library needs serial

API = "https://api.elevenlabs.io/v1"

# Prioritaeten-Sprachen (REIHENFOLGE ist wichtig fuer Budget-Allokation)
PRIORITY_LANGS = ["de", "en", "fr", "es", "it", "pt", "nl", "pl", "sv",
                  "no", "da", "fi", "cs", "sk", "ro", "hu", "el", "sl",
                  "hr", "lt", "lv", "et", "bg", "mt", "ga"]


def _env_file(name: str) -> dict[str, str]:
    path = ENV_DIR / name
    if not path.exists():
        return {}
    out: dict[str, str] = {}
    for line in path.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        k, v = line.split("=", 1)
        out[k.strip()] = v.strip()
    return out


def _tag_mp3(path: Path, provider: str, voice_name: str) -> None:
    try:
        from mutagen.mp3 import MP3  # type: ignore
        from mutagen.id3 import ID3, TPE1, COMM, TCOP  # type: ignore
        try:
            audio = MP3(str(path))
            if audio.tags is None:
                audio.add_tags()
            tag = audio.tags
        except Exception:
            tag = ID3()
        tag.add(TPE1(encoding=3, text=["Ghostforge"]))
        tag.add(COMM(encoding=3, lang="eng", desc="Source",
                     text=[f"Generated by voice-test.dev -- {provider} {voice_name}"]))
        tag.add(TCOP(encoding=3, text=["CC BY 4.0 -- voice-test.dev"]))
        if isinstance(tag, ID3):
            tag.save(str(path))
        else:
            audio.save()
    except Exception as e:
        print(f"    [tag warn] {path.name}: {e}", flush=True)


async def get_subscription(client: httpx.AsyncClient, key: str) -> dict:
    r = await client.get(f"{API}/user/subscription",
                         headers={"xi-api-key": key}, timeout=30.0)
    r.raise_for_status()
    return r.json()


async def fetch_default_voices(client: httpx.AsyncClient, key: str) -> list[dict]:
    r = await client.get(f"{API}/voices",
                         headers={"xi-api-key": key}, timeout=30.0)
    r.raise_for_status()
    out = []
    for v in r.json().get("voices", []):
        labels = v.get("labels", {}) or {}
        lang = labels.get("language", "en")
        out.append({
            "voice_id": v["voice_id"],
            "name": v.get("name", v["voice_id"]),
            "language": lang,
            "gender": labels.get("gender", "unknown"),
            "accent": labels.get("accent", ""),
            "category": "default",
            "preview_url": None,
        })
    return out


async def fetch_library_voices(
    client: httpx.AsyncClient,
    key: str,
    lang: str,
    gender: str | None,
    page_size: int = 50,
    max_pages: int = 4,
) -> list[dict]:
    """Paginiere shared-voices, sortiert nach usage_character_count_1y."""
    voices: list[dict] = []
    last_sort_id = None
    for _ in range(max_pages):
        params = {
            "page_size": str(page_size),
            "language": lang,
            "sort": "usage_character_count_1y",
        }
        if gender:
            params["gender"] = gender
        if last_sort_id:
            params["last_sort_id"] = last_sort_id
        r = await client.get(f"{API}/shared-voices",
                             headers={"xi-api-key": key},
                             params=params, timeout=30.0)
        if r.status_code != 200:
            print(f"  [warn] shared-voices {lang} {gender}: HTTP {r.status_code}",
                  flush=True)
            break
        data = r.json()
        batch = data.get("voices", [])
        if not batch:
            break
        for v in batch:
            voices.append({
                "voice_id": v["voice_id"],
                "name": v.get("name", v["voice_id"]),
                "language": v.get("language", lang),
                "gender": v.get("gender", "unknown"),
                "accent": v.get("accent", ""),
                "category": "library",
                "preview_url": v.get("preview_url"),
            })
        last_sort_id = data.get("last_sort_id")
        if not data.get("has_more"):
            break
    return voices


async def synth_one(
    client: httpx.AsyncClient,
    key: str,
    voice_id: str,
    text: str,
    out_path: Path,
) -> int:
    payload = {
        "text": text,
        "model_id": "eleven_multilingual_v2",
        "voice_settings": {"stability": 0.5, "similarity_boost": 0.75},
    }
    t0 = time.monotonic()
    for attempt in range(1, MAX_RETRIES + 2):
        try:
            r = await client.post(
                f"{API}/text-to-speech/{voice_id}",
                headers={"xi-api-key": key,
                         "Content-Type": "application/json",
                         "Accept": "audio/mpeg"},
                json=payload, timeout=90.0,
            )
            if r.status_code == 429:
                # Rate limit: warten und retry
                await asyncio.sleep(2.0 * attempt)
                continue
            if r.status_code != 200:
                raise RuntimeError(f"elevenlabs HTTP {r.status_code}: {r.text[:120]}")
            if len(r.content) < 256:
                raise RuntimeError("leere Audio-Antwort")
            out_path.write_bytes(r.content)
            return int((time.monotonic() - t0) * 1000)
        except httpx.HTTPError:
            if attempt > MAX_RETRIES:
                raise
            await asyncio.sleep(1.5 * attempt)
    return int((time.monotonic() - t0) * 1000)


async def main() -> int:
    env = _env_file("elevenlabs.env")
    if "ELEVENLABS_API_KEY" not in env:
        print("FEHLER: elevenlabs.env unvollstaendig", flush=True)
        return 1
    key = env["ELEVENLABS_API_KEY"]

    texts = json.loads(TEXTS_JSON.read_text(encoding="utf-8"))
    available_langs = set(texts["texts"]["v1_simple"].keys())

    async with httpx.AsyncClient() as client:
        sub = await get_subscription(client, key)
        char_limit = sub.get("character_limit", 0)
        char_used = sub.get("character_count", 0)
        char_remaining = char_limit - char_used
        print(f"Tier: {sub.get('tier')}, Limit: {char_limit}, "
              f"genutzt: {char_used}, remaining: {char_remaining}", flush=True)
        if char_remaining < 1000:
            print("WARNUNG: Budget fast erschöpft, nur noch "
                  f"{char_remaining} chars.", flush=True)

        # Default Voices holen
        default_voices = await fetch_default_voices(client, key)
        print(f"Default Voices: {len(default_voices)}", flush=True)

        # Voice Library: pro Sprache (in Prioritaeten-Reihenfolge)
        # DE female zuerst, dann DE male, dann EN, FR, ES, IT, etc.
        library_voices: list[dict] = []
        for lang in PRIORITY_LANGS:
            if lang not in available_langs:
                continue
            for gender in ["female", "male"]:
                # Pro lang/gender max 10 stimmen (sonst wirds zu viel)
                batch = await fetch_library_voices(
                    client, key, lang, gender,
                    page_size=10, max_pages=1,
                )
                library_voices.extend(batch[:10])
                if len(library_voices) >= 100:
                    break
            if len(library_voices) >= 100:
                break
        print(f"Voice Library (kumuliert): {len(library_voices)}", flush=True)

        all_voices = default_voices + library_voices
        # Dedup nach voice_id (falls Default Voices in Library sind)
        seen = set()
        unique_voices = []
        for v in all_voices:
            if v["voice_id"] in seen:
                continue
            seen.add(v["voice_id"])
            unique_voices.append(v)
        print(f"Total unique Stimmen: {len(unique_voices)}", flush=True)

        # Budget-Projektion: pro Stimme × 3 Varianten × ~100 chars
        avg_chars = sum(len(texts["texts"][v]["de"])
                        for v in VARIANTS
                        if "de" in texts["texts"][v]) / 3
        chars_per_voice = avg_chars * 3
        max_voices_by_budget = int(char_remaining / chars_per_voice)
        print(f"Budget erlaubt ~{max_voices_by_budget} Stimmen mit 3 Varianten",
              flush=True)
        # Voices auf das Budget-Limit kuerzen
        if len(unique_voices) > max_voices_by_budget:
            print(f"  -> kuerze auf {max_voices_by_budget} Stimmen", flush=True)
            unique_voices = unique_voices[:max_voices_by_budget]

        # Alte elevenlabs-Samples verwerfen, M52 generiert konsistent neu
        existing_raw = []
        if SAMPLES_JSON.exists():
            try:
                existing_raw = json.loads(
                    SAMPLES_JSON.read_text(encoding="utf-8")
                ).get("samples", [])
            except Exception:
                pass
        existing = [s for s in existing_raw
                    if s.get("provider") != "elevenlabs"]
        existing_ids = {s["id"] for s in existing}
        print(f"Bestand ohne elevenlabs: {len(existing)} Samples", flush=True)

        # Job-Plan: voice × variant (1 lang pro voice - ihre primary)
        plan_jobs: list[tuple] = []
        for v in unique_voices:
            lang = v["language"]
            if lang not in available_langs:
                lang = "en"  # Fallback, Multilingual kann alles
            safe_voice = "".join(
                c if c.isalnum() or c in "-_" else "_" for c in v["voice_id"]
            )
            for variant in VARIANTS:
                text = texts["texts"][variant].get(lang) or \
                       texts["texts"][variant].get("en")
                if not text:
                    continue
                sid = f"elevenlabs-{safe_voice}-{variant}"
                out_path = AUDIO_DIR / "elevenlabs" / safe_voice / f"{variant}.mp3"
                if sid in existing_ids:
                    continue
                if out_path.exists() and out_path.stat().st_size > 1024:
                    continue
                plan_jobs.append((v, lang, variant, text, sid, out_path))

        print(f"Plan: {len(plan_jobs)} Samples zu generieren", flush=True)
        if not plan_jobs:
            print("  Nichts zu tun.", flush=True)
            _write_samples(existing, [])
            return 0

        sem = asyncio.Semaphore(CONCURRENCY)
        counters = {"ok": 0, "err": 0, "chars": 0}
        errors: list[str] = []
        new_samples: list[dict] = []
        done = 0

        async def worker(v, lang, variant, text, sid, out_path):
            nonlocal done
            async with sem:
                out_path.parent.mkdir(parents=True, exist_ok=True)
                try:
                    ms = await synth_one(
                        client, key, v["voice_id"], text, out_path,
                    )
                    _tag_mp3(out_path, "elevenlabs", v["name"])
                    safe_voice = "".join(
                        c if c.isalnum() or c in "-_" else "_"
                        for c in v["voice_id"]
                    )
                    new_samples.append({
                        "id": sid,
                        "provider": "elevenlabs",
                        "provider_display": "ElevenLabs",
                        "voice_id": v["voice_id"],
                        "voice_name": v["name"],
                        "language": lang,
                        "language_name": next(
                            (l["name"] for l in texts.get("languages", [])
                             if l.get("code") == lang), lang),
                        "variant": variant,
                        "gender": v.get("gender", "unknown"),
                        "model_type": "eleven_multilingual_v2",
                        "category": v.get("category", "library"),
                        "accent": v.get("accent", ""),
                        "model_size_mb": None,
                        "audio_path": str(out_path.relative_to(ROOT)),
                        "provider_url": "https://elevenlabs.io",
                        "license": "proprietary",
                        "generation_time_ms": ms,
                        "sample_rate": 44100,
                    })
                    counters["ok"] += 1
                    counters["chars"] += len(text)
                except Exception as e:
                    counters["err"] += 1
                    errors.append(f"elevenlabs/{v['voice_id']}/{variant}: {e}")
                    if out_path.exists():
                        try:
                            out_path.unlink()
                        except Exception:
                            pass
                done += 1
                if done % 20 == 0:
                    sub = await get_subscription(client, key)
                    rem = sub["character_limit"] - sub["character_count"]
                    print(f"  Progress: {done}/{len(plan_jobs)} "
                          f"(ok={counters['ok']}, err={counters['err']}, "
                          f"chars_remaining={rem})", flush=True)
                    if rem < 500:
                        print("  STOP: Budget fast leer.", flush=True)
                        return "stop"
                return None

        tasks = [worker(*job) for job in plan_jobs]
        # Seriell in kleinen Batches, um Budget-Kontrolle zu behalten
        for i in range(0, len(tasks), 20):
            results = await asyncio.gather(*tasks[i:i + 20])
            if "stop" in results:
                print("Budget-Stop aktiviert.", flush=True)
                break
            # Budget live checken
            sub = await get_subscription(client, key)
            rem = sub["character_limit"] - sub["character_count"]
            if rem < 500:
                print(f"  Budget leer ({rem} chars), STOP.", flush=True)
                break

    # Disk-Sync
    for v in unique_voices:
        safe_voice = "".join(
            c if c.isalnum() or c in "-_" else "_" for c in v["voice_id"]
        )
        lang = v["language"]
        if lang not in available_langs:
            lang = "en"
        for variant in VARIANTS:
            sid = f"elevenlabs-{safe_voice}-{variant}"
            if sid in existing_ids:
                continue
            if any(s["id"] == sid for s in new_samples):
                continue
            out_path = AUDIO_DIR / "elevenlabs" / safe_voice / f"{variant}.mp3"
            if out_path.exists() and out_path.stat().st_size > 1024:
                new_samples.append({
                    "id": sid,
                    "provider": "elevenlabs",
                    "provider_display": "ElevenLabs",
                    "voice_id": v["voice_id"],
                    "voice_name": v["name"],
                    "language": lang,
                    "language_name": next(
                        (l["name"] for l in texts.get("languages", [])
                         if l.get("code") == lang), lang),
                    "variant": variant,
                    "gender": v.get("gender", "unknown"),
                    "model_type": "eleven_multilingual_v2",
                    "category": v.get("category", "library"),
                    "accent": v.get("accent", ""),
                    "model_size_mb": None,
                    "audio_path": str(out_path.relative_to(ROOT)),
                    "provider_url": "https://elevenlabs.io",
                    "license": "proprietary",
                    "generation_time_ms": None,
                    "sample_rate": 44100,
                })

    _write_samples(existing, new_samples)
    print(f"\nFertig: ok={counters['ok']}, err={counters['err']}, "
          f"chars_verbraucht={counters['chars']}", flush=True)
    if errors:
        print(f"Fehler ({len(errors)}):")
        for e in errors[:20]:
            print(f"  - {e}")
    return 0 if not errors else 1


def _write_samples(existing: list[dict], new_samples: list[dict]) -> None:
    all_samples = existing + new_samples
    SAMPLES_JSON.write_text(
        json.dumps({"_meta": {
            "generated_at": time.strftime("%Y-%m-%dT%H:%M:%S%z"),
            "total": len(all_samples),
        }, "samples": all_samples}, ensure_ascii=False, indent=2),
        encoding="utf-8",
    )
    print(f"samples.json: {len(all_samples)} Samples total", flush=True)


if __name__ == "__main__":
    sys.exit(asyncio.run(main()))
