#!/usr/bin/env python3
"""M51 S2b: Enterprise Sample-Generierung.

Liest data/texts.json + data/voices.json und generiert fuer jede Voice ×
unterstützte Sprache × Variante ein MP3-Sample. Output:
  audio/{provider}/{voice_id}/{lang}_{variant}.mp3
  data/samples.json (kumulative Metadaten, append-safe)

Concurrency-Limits pro Provider, um Rate-Limits zu respektieren.
Mutagen ID3-Tags fuer Attribution (Ghostforge / CC BY 4.0).

Optionen:
  --limit N      nur die ersten N Voices je Provider (Default: 10)
  --provider X   nur diesen Provider (Default: alle verfuegbaren)
  --dry-run      zeigt nur an, was gemacht wuerde, generiert aber nicht
"""
from __future__ import annotations

import argparse
import asyncio
import base64
import json
import os
import sys
import time
import traceback
from pathlib import Path

import httpx

DEVBRAIN_BACKEND = Path("/root/dev-brain/backend")
sys.path.insert(0, str(DEVBRAIN_BACKEND))
import secrets_vault  # noqa: E402

ROOT = Path(__file__).resolve().parent.parent
ENV_DIR = Path("/root/hermes-workspace/devbrain/.env")
AUDIO_DIR = ROOT / "audio"
SAMPLES_JSON = ROOT / "data" / "samples.json"
TEXTS_JSON = ROOT / "data" / "texts.json"
VOICES_JSON = ROOT / "data" / "voices.json"

CONCURRENCY = {"openai": 3, "azure": 5, "elevenlabs": 2, "edge": 8}
MAX_RETRIES = 2

VARIANTS = ["v1_simple", "v2_medium", "v3_emotional"]


def _env_file(name: str) -> dict[str, str]:
    path = ENV_DIR / name
    if not path.exists():
        return {}
    out: dict[str, str] = {}
    for line in path.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        k, v = line.split("=", 1)
        out[k.strip()] = v.strip()
    return out


def _tag_mp3(path: Path, provider: str, voice_name: str) -> None:
    """ID3-Tag mit Ghostforge/CC BY 4.0 Attribution."""
    try:
        from mutagen.mp3 import MP3  # type: ignore
        from mutagen.id3 import ID3, TPE1, COMM, TCOP  # type: ignore
        try:
            audio = MP3(str(path))
            if audio.tags is None:
                audio.add_tags()
            tag = audio.tags
        except Exception:  # noqa: BLE001 -- Datei hat noch kein ID3-Chunk
            tag = ID3()
        tag.add(TPE1(encoding=3, text=["Ghostforge"]))
        tag.add(COMM(encoding=3, lang="eng", desc="Source",
                     text=[f"Generated by voice-test.dev -- {provider} {voice_name}"]))
        tag.add(TCOP(encoding=3, text=["CC BY 4.0 -- voice-test.dev"]))
        if isinstance(tag, ID3):
            tag.save(str(path))
        else:
            audio.save()
    except Exception as e:  # noqa: BLE001 -- Tagging darf nie abbrechen
        print(f"    [tag warn] {path.name}: {e}", flush=True)


# ---------- Provider-Synth ----------
async def synth_openai(client: httpx.AsyncClient, voice: dict,
                       lang: str, variant: str, text: str, out_path: Path) -> None:
    key = await secrets_vault.get_secret("openai", "api_key")
    payload = {
        "model": "gpt-4o-mini-tts",
        "voice": voice["id"],
        "input": text,
        "response_format": "mp3",
    }
    r = await client.post(
        "https://api.openai.com/v1/audio/speech",
        headers={"Authorization": f"Bearer {key}"},
        json=payload, timeout=60.0,
    )
    if r.status_code != 200:
        raise RuntimeError(f"openai HTTP {r.status_code}: {r.text[:100]}")
    out_path.write_bytes(r.content)


async def synth_azure(client: httpx.AsyncClient, voice: dict,
                      lang: str, variant: str, text: str, out_path: Path) -> None:
    env = _env_file("azure.env")
    region = env["AZURE_SPEECH_REGION"]
    key = env["AZURE_SPEECH_KEY"]
    # SSML mit expliziter Voice + Language
    bcp47 = voice["id"]  # z.B. "de-DE-KatjaNeural"
    ssml = (
        f"<speak version='1.0' xml:lang='{bcp47[:5]}'>"
        f"<voice name='{bcp47}'>{text}</voice></speak>"
    )
    r = await client.post(
        f"https://{region}.tts.speech.microsoft.com/cognitiveservices/v1",
        headers={
            "Ocp-Apim-Subscription-Key": key,
            "Content-Type": "application/ssml+xml",
            "X-Microsoft-OutputFormat": "audio-24khz-48kbitrate-mono-mp3",
        },
        content=ssml, timeout=60.0,
    )
    if r.status_code != 200:
        raise RuntimeError(f"azure HTTP {r.status_code}: {r.text[:100]}")
    out_path.write_bytes(r.content)


async def synth_elevenlabs(client: httpx.AsyncClient, voice: dict,
                           lang: str, variant: str, text: str, out_path: Path) -> None:
    env = _env_file("elevenlabs.env")
    key = env["ELEVENLABS_API_KEY"]
    payload = {
        "text": text,
        "model_id": "eleven_multilingual_v2",
        "voice_settings": {"stability": 0.5, "similarity_boost": 0.75},
    }
    r = await client.post(
        f"https://api.elevenlabs.io/v1/text-to-speech/{voice['id']}",
        headers={"xi-api-key": key, "Content-Type": "application/json",
                 "Accept": "audio/mpeg"},
        json=payload, timeout=90.0,
    )
    if r.status_code != 200:
        raise RuntimeError(f"elevenlabs HTTP {r.status_code}: {r.text[:100]}")
    out_path.write_bytes(r.content)


async def synth_edge(client: httpx.AsyncClient, voice: dict,
                     lang: str, variant: str, text: str, out_path: Path) -> None:
    import edge_tts  # type: ignore
    comm = edge_tts.Communicate(text, voice["id"])
    # edge_tts ist async, nutzt eigenen Client -- nicht httpx
    await comm.save(str(out_path))


SYNTH = {
    "openai": synth_openai,
    "azure": synth_azure,
    "elevenlabs": synth_elevenlabs,
    "edge": synth_edge,
}


async def _gen_one(
    sem: asyncio.Semaphore,
    client: httpx.AsyncClient,
    provider: str,
    voice: dict,
    lang: str,
    variant: str,
    text: str,
    texts_meta: dict,
    counters: dict,
    errors: list,
    samples: list,
):
    async with sem:
        voice_id = voice["id"]
        safe_voice = "".join(c if c.isalnum() or c in "-_" else "_" for c in voice_id)
        out_dir = AUDIO_DIR / provider / safe_voice
        out_dir.mkdir(parents=True, exist_ok=True)
        out_path = out_dir / f"{lang}_{variant}.mp3"
        if out_path.exists() and out_path.stat().st_size > 1024:
            counters["skip"] += 1
            return
        for attempt in range(1, MAX_RETRIES + 2):
            try:
                t0 = time.monotonic()
                await SYNTH[provider](client, voice, lang, variant, text, out_path)
                if not out_path.exists() or out_path.stat().st_size < 1024:
                    raise RuntimeError("leere oder fehlende Datei")
                _tag_mp3(out_path, provider, voice.get("name", voice_id))
                ms = int((time.monotonic() - t0) * 1000)
                samples.append({
                    "id": f"{provider}-{safe_voice}-{lang}-{variant}",
                    "provider": provider,
                    "provider_display": {
                        "openai": "OpenAI",
                        "azure": "Microsoft Azure",
                        "elevenlabs": "ElevenLabs",
                        "edge": "Microsoft Edge TTS",
                    }.get(provider, provider),
                    "voice_id": voice_id,
                    "voice_name": voice.get("name", voice_id),
                    "language": lang,
                    "language_name": next(
                        (l["name"] for l in texts_meta["languages"]
                         if l["code"] == lang), lang),
                    "variant": variant,
                    "gender": voice.get("gender", "unknown"),
                    "model_type": voice.get("type", "unknown"),
                    "model_size_mb": None,
                    "audio_path": str(out_path.relative_to(ROOT)),
                    "provider_url": {
                        "openai": "https://platform.openai.com/docs/guides/text-to-speech",
                        "azure": "https://azure.microsoft.com/products/ai-services/text-to-speech",
                        "elevenlabs": "https://elevenlabs.io",
                        "edge": "https://github.com/rany2/edge-tts",
                    }.get(provider, ""),
                    "license": "proprietary",
                    "generation_time_ms": ms,
                    "sample_rate": 24000,
                })
                counters["ok"] += 1
                return
            except Exception as e:  # noqa: BLE001
                if attempt > MAX_RETRIES:
                    counters["err"] += 1
                    errors.append(f"{provider}/{voice_id}/{lang}_{variant}: {e}")
                    if out_path.exists():
                        try:
                            out_path.unlink()
                        except Exception:  # noqa: BLE001
                            pass
                    return
                await asyncio.sleep(1.5 * attempt)


async def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--limit", type=int, default=10,
                    help="max voices pro provider (0 = alle)")
    ap.add_argument("--provider", default=None,
                    help="nur diesen Provider")
    ap.add_argument("--dry-run", action="store_true")
    args = ap.parse_args()

    texts = json.loads(TEXTS_JSON.read_text(encoding="utf-8"))
    voices_data = json.loads(VOICES_JSON.read_text(encoding="utf-8"))

    # existierende samples laden (append-safe)
    existing: list[dict] = []
    if SAMPLES_JSON.exists():
        try:
            existing = json.loads(SAMPLES_JSON.read_text(encoding="utf-8")).get("samples", [])
        except Exception:  # noqa: BLE001
            existing = []

    # Bestimmte Provider-ID für Sample-ID Dedup (vorhandene IDs überspringen)
    existing_ids = {s["id"] for s in existing}

    samples: list[dict] = []
    errors: list[str] = []
    counters = {"ok": 0, "skip": 0, "err": 0}

    plan_total = 0
    plan_by_provider: dict[str, int] = {}
    plan_jobs: list[tuple] = []  # (provider, voice, lang, variant, text)

    for prov_name, prov in voices_data["providers"].items():
        if not prov.get("_available"):
            continue
        if args.provider and prov_name != args.provider:
            continue
        voices = prov["voices"]
        if args.limit and args.limit > 0:
            voices = voices[:args.limit]
        for v in voices:
            for lang in v["languages"]:
                if lang not in texts["texts"]["v1_simple"]:
                    continue
                for variant in VARIANTS:
                    text = texts["texts"][variant].get(lang)
                    if not text:
                        continue
                    sid = f"{prov_name}-{v['id']}-{lang}-{variant}"
                    # bereits vorhandene Samples überspringen
                    out_path_check = (
                        AUDIO_DIR / prov_name /
                        "".join(c if c.isalnum() or c in "-_" else "_" for c in v["id"])
                        / f"{lang}_{variant}.mp3"
                    )
                    if sid in existing_ids or (
                        out_path_check.exists() and out_path_check.stat().st_size > 1024
                    ):
                        continue
                    plan_total += 1
                    plan_by_provider[prov_name] = plan_by_provider.get(prov_name, 0) + 1
                    plan_jobs.append((prov_name, v, lang, variant, text))

    print(f"S2b: {plan_total} Samples zu generieren", flush=True)
    for p, n in plan_by_provider.items():
        print(f"  {p:>12}: {n}", flush=True)

    if args.dry_run or plan_total == 0:
        if plan_total == 0 and existing:
            print(f"  Nichts zu tun -- {len(existing)} Samples bereits vorhanden.", flush=True)
        return 0

    t0 = time.monotonic()
    async with httpx.AsyncClient() as client:
        # Pro Provider eine eigene Queue, damit Concurrency getrennt ist
        per_provider: dict[str, list] = {p: [] for p in plan_by_provider}
        for job in plan_jobs:
            per_provider[job[0]].append(job)
        tasks = []
        for prov_name, jobs in per_provider.items():
            sem = asyncio.Semaphore(CONCURRENCY.get(prov_name, 2))
            for prov_name_, v, lang, variant, text in jobs:
                tasks.append(_gen_one(
                    sem, client, prov_name_, v, lang, variant, text,
                    texts, counters, errors, samples,
                ))
        # in Chunks laufen lassen, damit Print-Progress sichtbar wird
        chunk_size = 50
        for i in range(0, len(tasks), chunk_size):
            await asyncio.gather(*tasks[i:i + chunk_size])
            done = counters["ok"] + counters["err"] + counters["skip"]
            print(f"  Progress: {done}/{plan_total} "
                  f"(ok={counters['ok']}, skip={counters['skip']}, err={counters['err']})",
                  flush=True)

    duration = time.monotonic() - t0
    print(f"\nFertig in {duration:.1f}s", flush=True)
    print(f"  ok={counters['ok']}, skip={counters['skip']}, err={counters['err']}",
          flush=True)
    if errors:
        print(f"\nFehler ({len(errors)}):")
        for e in errors[:30]:
            print(f"  - {e}")

    # samples.json aktualisieren
    all_samples = existing + samples
    SAMPLES_JSON.write_text(
        json.dumps({"_meta": {
            "generated_at": time.strftime("%Y-%m-%dT%H:%M:%S%z"),
            "total": len(all_samples),
        }, "samples": all_samples}, ensure_ascii=False, indent=2),
        encoding="utf-8",
    )
    print(f"\nsamples.json: {len(all_samples)} Samples total", flush=True)
    return 0 if not errors else 1


if __name__ == "__main__":
    sys.exit(asyncio.run(main()))
