#!/usr/bin/env python3
"""M51 Aufgabe 2: Knowlez TTS Sample-Generierung.

Knowlez ist ein kommerzieller Wrapper um Kokoro-82M mit REST-API.
Trial-Limit: 5 Calls insgesamt (4 nach 1 verbrauchten).
Daher keine Vollabdeckung, sondern repraesentative Stichprobe:
Default-Stimme af_bella × 3 DE-Varianten + 1 EN-Variante = 4 Samples.

Endpoint: POST https://api-tts.knowlez.com/v1/tts/synthesise
Header:   x-api-key: <key>
Body:     {"text": "...", "voice": "af_bella", "format": "mp3"}

Output:
  audio/knowlez/{voice_id}/{lang}_{variant}.mp3
  data/samples.json (append-safe)

Keys aus /root/hermes-workspace/devbrain/.env/knowlez.env
"""
from __future__ import annotations

import json
import sys
import time
from pathlib import Path

import httpx

ROOT = Path(__file__).resolve().parent.parent
ENV_DIR = Path("/root/hermes-workspace/devbrain/.env")
AUDIO_DIR = ROOT / "audio"
SAMPLES_JSON = ROOT / "data" / "samples.json"
TEXTS_JSON = ROOT / "data" / "texts.json"

# Repraesentative Stichprobe wegen Trial-Limit (4 Calls frei)
JOBS = [
    # (voice_id, voice_name, language, variant)
    ("af_bella", "af_bella (weiblich, EN-Mutter)", "de", "v1_simple"),
    ("af_bella", "af_bella (weiblich, EN-Mutter)", "de", "v2_medium"),
    ("af_bella", "af_bella (weiblich, EN-Mutter)", "de", "v3_emotional"),
    ("af_bella", "af_bella (weiblich, EN-Mutter)", "en", "v1_simple"),
]


def _env_file(name: str) -> dict[str, str]:
    path = ENV_DIR / name
    if not path.exists():
        return {}
    out: dict[str, str] = {}
    for line in path.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        k, v = line.split("=", 1)
        out[k.strip()] = v.strip()
    return out


def _tag_mp3(path: Path, provider: str, voice_name: str) -> None:
    try:
        from mutagen.mp3 import MP3  # type: ignore
        from mutagen.id3 import ID3, TPE1, COMM, TCOP  # type: ignore
        try:
            audio = MP3(str(path))
            if audio.tags is None:
                audio.add_tags()
            tag = audio.tags
        except Exception:
            tag = ID3()
        tag.add(TPE1(encoding=3, text=["Ghostforge"]))
        tag.add(COMM(encoding=3, lang="eng", desc="Source",
                     text=[f"Generated by voice-test.dev -- {provider} {voice_name}"]))
        tag.add(TCOP(encoding=3, text=["CC BY 4.0 -- voice-test.dev"]))
        if isinstance(tag, ID3):
            tag.save(str(path))
        else:
            audio.save()
    except Exception as e:
        print(f"    [tag warn] {path.name}: {e}", flush=True)


def main() -> int:
    env = _env_file("knowlez.env")
    if not env:
        print("FEHLER: knowlez.env nicht gefunden", flush=True)
        return 1
    key = env["KNOWLEZ_API_KEY"]
    endpoint = env.get("KNOWLEZ_ENDPOINT",
                       "https://api-tts.knowlez.com/v1/tts/synthesise")

    texts = json.loads(TEXTS_JSON.read_text(encoding="utf-8"))
    existing = []
    if SAMPLES_JSON.exists():
        try:
            existing = json.loads(
                SAMPLES_JSON.read_text(encoding="utf-8")
            ).get("samples", [])
        except Exception:
            pass
    existing_ids = {s["id"] for s in existing}

    new_samples: list[dict] = []
    errors: list[str] = []

    with httpx.Client(timeout=60.0) as client:
        for voice_id, voice_name, lang, variant in JOBS:
            sid = f"knowlez-{voice_id}-{lang}-{variant}"
            if sid in existing_ids:
                print(f"  SKIP {sid} (bereits vorhanden)", flush=True)
                continue
            text = texts["texts"][variant].get(lang)
            if not text:
                print(f"  SKIP {sid}: kein Text fuer {lang}", flush=True)
                continue
            out_dir = AUDIO_DIR / "knowlez" / voice_id
            out_dir.mkdir(parents=True, exist_ok=True)
            out_path = out_dir / f"{lang}_{variant}.mp3"
            if out_path.exists() and out_path.stat().st_size > 1024:
                print(f"  SKIP {sid}: Datei existiert", flush=True)
                continue

            t0 = time.monotonic()
            try:
                r = client.post(
                    endpoint,
                    headers={
                        "x-api-key": key,
                        "Content-Type": "application/json",
                    },
                    json={
                        "text": text,
                        "voice": voice_id,
                        "format": "mp3",
                        "speed": 1.0,
                    },
                )
                if r.status_code not in (200, 201):
                    raise RuntimeError(
                        f"knowlez HTTP {r.status_code}: {r.text[:200]}"
                    )
                if len(r.content) < 256:
                    raise RuntimeError("leere Audio-Antwort")
                out_path.write_bytes(r.content)
                _tag_mp3(out_path, "knowlez", voice_name)
                ms = int((time.monotonic() - t0) * 1000)
                new_samples.append({
                    "id": sid,
                    "provider": "knowlez",
                    "provider_display": "Knowlez",
                    "voice_id": voice_id,
                    "voice_name": voice_name,
                    "language": lang,
                    "language_name": next(
                        (l["name"] for l in texts.get("languages", [])
                         if l.get("code") == lang), lang),
                    "variant": variant,
                    "gender": "female" if voice_id.startswith(("af_", "bf_")) else "male",
                    "model_type": "neural",
                    "model_size_mb": 82,
                    "audio_path": str(out_path.relative_to(ROOT)),
                    "provider_url": "https://knowlez.com",
                    "license": "proprietary",
                    "generation_time_ms": ms,
                    "sample_rate": 24000,
                    "_note": "Trial-Limit: nur 5 API-Calls, repraesentative Stichprobe",
                })
                print(f"  OK {sid} ({len(r.content)} bytes)", flush=True)
            except Exception as e:
                errors.append(f"knowlez/{voice_id}/{lang}_{variant}: {e}")
                print(f"  ERR {sid}: {e}", flush=True)
                if out_path.exists():
                    try:
                        out_path.unlink()
                    except Exception:
                        pass

    all_samples = existing + new_samples
    SAMPLES_JSON.write_text(
        json.dumps({"_meta": {
            "generated_at": time.strftime("%Y-%m-%dT%H:%M:%S%z"),
            "total": len(all_samples),
        }, "samples": all_samples}, ensure_ascii=False, indent=2),
        encoding="utf-8",
    )
    print(f"\nsamples.json: {len(all_samples)} Samples total", flush=True)
    print(f"ok={len(new_samples)}, err={len(errors)}", flush=True)
    return 0 if not errors else 1


if __name__ == "__main__":
    sys.exit(main())
