#!/usr/bin/env python3
"""M52 S1f: OpenAI TTS - ALLE Stimmen × ALLE Modelle.

Modelle: tts-1, tts-1-hd, gpt-4o-mini-tts
Stimmen: alloy, ash, ballad, coral, echo, fable, nova, onyx, sage, shimmer
('ballad' ist nur in gpt-4o-mini-tts verfuegbar, nicht tts-1/tts-1-hd)

Pro Stimme × Modell × 25 EU-Sprachen × 3 Varianten.

Output:
  audio/openai/{voice_id}/{model}_{lang}_{variant}.mp3
  data/samples.json (existing openai-Samples werden gefiltert)
"""
from __future__ import annotations

import asyncio
import json
import sys
import time
from pathlib import Path

import httpx

ROOT = Path(__file__).resolve().parent.parent
DEVBR = Path("/root/dev-brain/backend")
sys.path.insert(0, str(DEVBR))
import secrets_vault  # noqa: E402

AUDIO_DIR = ROOT / "audio"
SAMPLES_JSON = ROOT / "data" / "samples.json"
TEXTS_JSON = ROOT / "data" / "texts.json"

VARIANTS = ["v1_simple", "v2_medium", "v3_emotional"]
MAX_RETRIES = 2
CONCURRENCY = 10  # OpenAI erlaubt hoch, gpt-4o-mini-tts ist billig

# Voice × Modell Kompatibilität (getestet)
VOICES_PER_MODEL = {
    "gpt-4o-mini-tts": [
        "alloy", "ash", "ballad", "coral", "echo",
        "fable", "nova", "onyx", "sage", "shimmer",
    ],
    "tts-1": [
        "alloy", "ash", "coral", "echo",
        "fable", "nova", "onyx", "sage", "shimmer",
        # 'ballad' ist nicht verfuegbar in tts-1
    ],
    "tts-1-hd": [
        "alloy", "ash", "coral", "echo",
        "fable", "nova", "onyx", "sage", "shimmer",
    ],
}


def _tag_mp3(path: Path, provider: str, voice_name: str) -> None:
    try:
        from mutagen.mp3 import MP3  # type: ignore
        from mutagen.id3 import ID3, TPE1, COMM, TCOP  # type: ignore
        try:
            audio = MP3(str(path))
            if audio.tags is None:
                audio.add_tags()
            tag = audio.tags
        except Exception:
            tag = ID3()
        tag.add(TPE1(encoding=3, text=["Ghostforge"]))
        tag.add(COMM(encoding=3, lang="eng", desc="Source",
                     text=[f"Generated by voice-test.dev -- {provider} {voice_name}"]))
        tag.add(TCOP(encoding=3, text=["CC BY 4.0 -- voice-test.dev"]))
        if isinstance(tag, ID3):
            tag.save(str(path))
        else:
            audio.save()
    except Exception as e:
        print(f"    [tag warn] {path.name}: {e}", flush=True)


async def synth_one(
    client: httpx.AsyncClient,
    key: str,
    voice: str,
    model: str,
    text: str,
    out_path: Path,
) -> int:
    payload = {
        "model": model,
        "voice": voice,
        "input": text,
        "response_format": "mp3",
    }
    t0 = time.monotonic()
    for attempt in range(1, MAX_RETRIES + 2):
        try:
            r = await client.post(
                "https://api.openai.com/v1/audio/speech",
                headers={"Authorization": f"Bearer {key}"},
                json=payload, timeout=60.0,
            )
            if r.status_code == 429:
                await asyncio.sleep(2.0 * attempt)
                continue
            if r.status_code != 200:
                raise RuntimeError(f"openai HTTP {r.status_code}: {r.text[:120]}")
            if len(r.content) < 256:
                raise RuntimeError("leere Audio-Antwort")
            out_path.write_bytes(r.content)
            return int((time.monotonic() - t0) * 1000)
        except httpx.HTTPError:
            if attempt > MAX_RETRIES:
                raise
            await asyncio.sleep(1.5 * attempt)
    return int((time.monotonic() - t0) * 1000)


async def main() -> int:
    key = await secrets_vault.get_secret("openai", "api_key")
    if not key:
        print("FEHLER: openai api_key fehlt", flush=True)
        return 1

    texts = json.loads(TEXTS_JSON.read_text(encoding="utf-8"))
    available_langs = set(texts["texts"]["v1_simple"].keys())

    # Alte openai-Samples verwerfen
    existing_raw = []
    if SAMPLES_JSON.exists():
        try:
            existing_raw = json.loads(
                SAMPLES_JSON.read_text(encoding="utf-8")
            ).get("samples", [])
        except Exception:
            pass
    existing = [s for s in existing_raw if s.get("provider") != "openai"]
    existing_ids = {s["id"] for s in existing}
    print(f"Bestand ohne openai: {len(existing)} Samples", flush=True)

    # Job-Plan
    plan_jobs: list[tuple] = []
    for model, voices in VOICES_PER_MODEL.items():
        safe_model = model.replace(".", "_").replace("-", "_")
        for voice in voices:
            safe_voice = "".join(
                c if c.isalnum() or c in "-_" else "_" for c in voice
            )
            for lang in sorted(available_langs):
                for variant in VARIANTS:
                    text = texts["texts"][variant].get(lang)
                    if not text:
                        continue
                    sid = f"openai-{voice}-{model}-{lang}-{variant}"
                    out_path = (
                        AUDIO_DIR / "openai" / safe_voice
                        / f"{safe_model}_{lang}_{variant}.mp3"
                    )
                    if sid in existing_ids:
                        continue
                    if out_path.exists() and out_path.stat().st_size > 1024:
                        continue
                    plan_jobs.append((voice, model, lang, variant, text,
                                      sid, out_path))

    print(f"Plan: {len(plan_jobs)} Samples "
          f"(10v × 3m × 25l × 3v = max 2250)", flush=True)
    if not plan_jobs:
        print("  Nichts zu tun.")
        _write_samples(existing, [])
        return 0

    sem = asyncio.Semaphore(CONCURRENCY)
    counters = {"ok": 0, "err": 0}
    errors: list[str] = []
    new_samples: list[dict] = []
    done = 0

    async def worker(voice, model, lang, variant, text, sid, out_path):
        nonlocal done
        async with sem:
            out_path.parent.mkdir(parents=True, exist_ok=True)
            try:
                ms = await synth_one(
                    client, key, voice, model, text, out_path,
                )
                _tag_mp3(out_path, "openai", f"{voice}/{model}")
                safe_voice = "".join(
                    c if c.isalnum() or c in "-_" else "_" for c in voice
                )
                safe_model = model.replace(".", "_").replace("-", "_")
                new_samples.append({
                    "id": sid,
                    "provider": "openai",
                    "provider_display": "OpenAI TTS",
                    "voice_id": voice,
                    "voice_name": voice,
                    "language": lang,
                    "language_name": next(
                        (l["name"] for l in texts.get("languages", [])
                         if l.get("code") == lang), lang),
                    "model": model,
                    "variant": variant,
                    "gender": "unknown",  # OpenAI spezifiziert kein Geschlecht
                    "model_type": model,
                    "model_size_mb": None,
                    "audio_path": str(out_path.relative_to(ROOT)),
                    "provider_url": "https://platform.openai.com/docs/guides/text-to-speech",
                    "license": "proprietary",
                    "generation_time_ms": ms,
                    "sample_rate": 24000,
                })
                counters["ok"] += 1
            except Exception as e:
                counters["err"] += 1
                errors.append(f"openai/{voice}/{model}/{lang}_{variant}: {e}")
                if out_path.exists():
                    try:
                        out_path.unlink()
                    except Exception:
                        pass
            done += 1
            if done % 100 == 0:
                print(f"  Progress: {done}/{len(plan_jobs)} "
                      f"(ok={counters['ok']}, err={counters['err']})",
                      flush=True)

    async with httpx.AsyncClient() as client:
        tasks = [worker(*job) for job in plan_jobs]
        for i in range(0, len(tasks), 30):
            await asyncio.gather(*tasks[i:i + 30])

    # Disk-Sync
    audio_openai = AUDIO_DIR / "openai"
    if audio_openai.exists():
        for voice_dir in audio_openai.iterdir():
            if not voice_dir.is_dir():
                continue
            voice = voice_dir.name
            for mp3 in voice_dir.glob("*.mp3"):
                # filename: {model}_{lang}_{variant}.mp3
                parts = mp3.stem.split("_", 2)
                if len(parts) != 3:
                    continue
                safe_model, lang, variant = parts
                # model wiederherstellen (z.B. gpt_4o_mini_tts -> gpt-4o-mini-tts)
                model_map_inv = {
                    "gpt_4o_mini_tts": "gpt-4o-mini-tts",
                    "tts_1": "tts-1",
                    "tts_1_hd": "tts-1-hd",
                }
                model = model_map_inv.get(safe_model, safe_model)
                sid = f"openai-{voice}-{model}-{lang}-{variant}"
                if sid in existing_ids:
                    continue
                if any(s["id"] == sid for s in new_samples):
                    continue
                new_samples.append({
                    "id": sid,
                    "provider": "openai",
                    "provider_display": "OpenAI TTS",
                    "voice_id": voice,
                    "voice_name": voice,
                    "language": lang,
                    "language_name": next(
                        (l["name"] for l in texts.get("languages", [])
                         if l.get("code") == lang), lang),
                    "model": model,
                    "variant": variant,
                    "gender": "unknown",
                    "model_type": model,
                    "model_size_mb": None,
                    "audio_path": str(mp3.relative_to(ROOT)),
                    "provider_url": "https://platform.openai.com/docs/guides/text-to-speech",
                    "license": "proprietary",
                    "generation_time_ms": None,
                    "sample_rate": 24000,
                })

    _write_samples(existing, new_samples)
    print(f"\nFertig: ok={counters['ok']}, err={counters['err']}", flush=True)
    if errors:
        print(f"Fehler ({len(errors)}):")
        for e in errors[:20]:
            print(f"  - {e}")
    return 0 if not errors else 1


def _write_samples(existing: list[dict], new_samples: list[dict]) -> None:
    all_samples = existing + new_samples
    SAMPLES_JSON.write_text(
        json.dumps({"_meta": {
            "generated_at": time.strftime("%Y-%m-%dT%H:%M:%S%z"),
            "total": len(all_samples),
        }, "samples": all_samples}, ensure_ascii=False, indent=2),
        encoding="utf-8",
    )
    print(f"samples.json: {len(all_samples)} Samples total", flush=True)


if __name__ == "__main__":
    sys.exit(asyncio.run(main()))
